title: Rob's Hypertext Notebook
name: Rob Haisfield
user_description: Behavioral product strategist and gamification designer. This is my public hypertext notebook, sharing my thinking in motion at various stages of development.
notes_url: "https://robhaisfield.com"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
copyright_name: Rob Haisfield
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://robhaisfield.com" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# Social Media Links
twitter: https://www.twitter.com/RobertHaisfield
emailid: rob@influenceinsights.io
personal_site_name: Scaling Synthesis
personal_site_url: https://scalingsynthesis.com/
linkedin:
github:

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname:
  #robhaisfield  # Please correct this with your discus username

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
  notes:
    output: true
    permalink: /notes/:title

feed:
  collections:
    notes:
      path: "/notes/feed.xml"

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
      comments: true
