title: Thinking in Webs
name: Rob Haisfield
user_description: Behavioral product strategist and gamification designer. Always working on multiple things at once.
notes_url: "https://robhaisfield.com"
profile_pic: /assets/img/headshot.jpeg
favicon: /assets/img/favicon.png
copyright_name: Rob Haisfield
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://robhaisfield.com" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
