title: Webs of Influence
name: Rob Haisfield
user_description: Behavioral product strategist and gamification designer. I read a lot of behavioral science papers, play a lot of video games, and apply what I learn to make products that people love. Contact me on Twitter (@RobertHaisfield), email (rob@influenceinsights.io), or my website ( https://www.influenceinsights.io/ )
notes_url: "https://robhaisfield.com"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
copyright_name: Rob Haisfield
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://robhaisfield.com" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8
google_analytics: UA-172451684-1


# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
